/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'directReferrals' : bigint,
  'rightTeamCount' : bigint,
  'totalIncome' : bigint,
  'totalTeam' : bigint,
  'recentIncomeRecords' : Array<IncomeRecord>,
  'leftTeamCount' : bigint,
  'walletBalance' : bigint,
}
export interface IncomeRecord {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : bigint,
  'level' : [] | [bigint],
  'fromUserId' : UserId,
  'incomeType' : { 'level' : null } |
    { 'direct' : null } |
    { 'binary' : null },
  'amount' : bigint,
}
export interface Payment {
  'id' : bigint,
  'status' : { 'verified' : null } |
    { 'pending' : null } |
    { 'rejected' : null },
  'planId' : bigint,
  'userId' : UserId,
  'createdAt' : bigint,
  'upiRef' : string,
  'amount' : bigint,
}
export interface Plan {
  'id' : bigint,
  'levelIncomeRates' : Array<bigint>,
  'directIncomePercent' : bigint,
  'name' : string,
  'binaryIncomePercent' : bigint,
  'price' : bigint,
}
export type Position = { 'left' : null } |
  { 'right' : null };
export type PaymentStatus_candid = { 'pendingVerification' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'price' : bigint,
}
export type SessionToken = string;
export interface User {
  'id' : UserId,
  'directIncome' : bigint,
  'planId' : bigint,
  'rightTeamCount' : bigint,
  'joinedAt' : bigint,
  'rightChildId' : [] | [UserId],
  'totalIncome' : bigint,
  'levelIncome' : bigint,
  'fullName' : string,
  'leftChildId' : [] | [UserId],
  'isActive' : boolean,
  'binaryIncome' : bigint,
  'myReferralCode' : string,
  'mobile' : string,
  'position' : [] | [Position],
  'parentId' : [] | [UserId],
  'leftTeamCount' : bigint,
  'walletBalance' : bigint,
  'sponsorCode' : string,
  'utrNumber' : string,
  'screenshotUrl' : string,
  'paymentStatus' : PaymentStatus_candid,
}
export interface UserDto {
  'id' : UserId,
  'directIncome' : bigint,
  'planId' : bigint,
  'rightTeamCount' : bigint,
  'joinedAt' : bigint,
  'totalIncome' : bigint,
  'levelIncome' : bigint,
  'fullName' : string,
  'binaryIncome' : bigint,
  'myReferralCode' : string,
  'mobile' : string,
  'leftTeamCount' : bigint,
  'walletBalance' : bigint,
  'sponsorCode' : string,
  'isActive' : boolean,
  'paymentStatus' : PaymentStatus_candid,
}
export interface UserRegistrationDto {
  'id' : UserId,
  'fullName' : string,
  'mobile' : string,
  'planId' : bigint,
  'planName' : string,
  'planPrice' : bigint,
  'utrNumber' : string,
  'screenshotUrl' : string,
  'paymentStatus' : PaymentStatus_candid,
  'joinedAt' : bigint,
}
export type UserId = string;
export interface UserProfile {
  'userId' : string,
  'fullName' : string,
  'myReferralCode' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : UserId,
  'note' : string,
  'createdAt' : bigint,
  'txType' : { 'credit' : null } |
    { 'debit' : null },
  'amount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, bigint, string], bigint>,
  'addUserBinaryPosition' : ActorMethod<[UserId, UserId, Position], undefined>,
  'adminActivateUser' : ActorMethod<[UserId, boolean], undefined>,
  'adminApproveRegistration' : ActorMethod<[UserId, boolean], undefined>,
  'adminApproveWithdraw' : ActorMethod<[bigint, boolean], undefined>,
  'adminGetPayments' : ActorMethod<[], Array<Payment>>,
  'adminGetPendingRegistrations' : ActorMethod<[], Array<UserRegistrationDto>>,
  'adminGetProducts' : ActorMethod<[], Array<Product>>,
  'adminGetTotalBusiness' : ActorMethod<
    [],
    {
      'totalIncomeDistributed' : bigint,
      'totalPlansSold' : bigint,
      'totalUsers' : bigint,
      'totalWithdrawals' : bigint,
    }
  >,
  'adminLogin' : ActorMethod<[string], SessionToken>,
  'adminUserList' : ActorMethod<[], Array<UserDto>>,
  'adminVerifyPayment' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateBinaryIncome' : ActorMethod<[UserId], bigint>,
  'getBinaryTree' : ActorMethod<
    [UserId],
    [] | [
      { 'left' : [] | [UserDto], 'user' : UserDto, 'right' : [] | [UserDto] }
    ]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlans' : ActorMethod<[], Array<Plan>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserDashboard' : ActorMethod<[SessionToken], [] | [DashboardStats]>,
  'getUserIncomeRecords' : ActorMethod<[SessionToken], Array<IncomeRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileById' : ActorMethod<[SessionToken], [] | [User]>,
  'getUserWalletHistory' : ActorMethod<
    [SessionToken],
    Array<WalletTransaction>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUserByMobile' : ActorMethod<[string, string], SessionToken>,
  'registerUser' : ActorMethod<[string, string, string, bigint, string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendOTP' : ActorMethod<[string], string>,
  'submitPayment' : ActorMethod<[SessionToken, bigint, string], bigint>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, boolean],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[SessionToken, string], undefined>,
  'verifyOTP' : ActorMethod<[string, string], boolean>,
  'withdrawRequest' : ActorMethod<[SessionToken, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
