/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Position = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'planId' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : IDL.Int,
  'upiRef' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const SessionToken = IDL.Text;
export const UserDto = IDL.Record({
  'id' : UserId,
  'directIncome' : IDL.Nat,
  'planId' : IDL.Nat,
  'rightTeamCount' : IDL.Nat,
  'joinedAt' : IDL.Int,
  'totalIncome' : IDL.Nat,
  'levelIncome' : IDL.Nat,
  'fullName' : IDL.Text,
  'binaryIncome' : IDL.Nat,
  'myReferralCode' : IDL.Text,
  'mobile' : IDL.Text,
  'leftTeamCount' : IDL.Nat,
  'walletBalance' : IDL.Nat,
  'sponsorCode' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'fullName' : IDL.Text,
  'myReferralCode' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Plan = IDL.Record({
  'id' : IDL.Nat,
  'levelIncomeRates' : IDL.Vec(IDL.Nat),
  'directIncomePercent' : IDL.Nat,
  'name' : IDL.Text,
  'binaryIncomePercent' : IDL.Nat,
  'price' : IDL.Nat,
});
export const IncomeRecord = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : IDL.Int,
  'level' : IDL.Opt(IDL.Nat),
  'fromUserId' : UserId,
  'incomeType' : IDL.Variant({
    'level' : IDL.Null,
    'direct' : IDL.Null,
    'binary' : IDL.Null,
  }),
  'amount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'directReferrals' : IDL.Nat,
  'rightTeamCount' : IDL.Nat,
  'totalIncome' : IDL.Nat,
  'totalTeam' : IDL.Nat,
  'recentIncomeRecords' : IDL.Vec(IncomeRecord),
  'leftTeamCount' : IDL.Nat,
  'walletBalance' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : UserId,
  'directIncome' : IDL.Nat,
  'planId' : IDL.Nat,
  'rightTeamCount' : IDL.Nat,
  'joinedAt' : IDL.Int,
  'rightChildId' : IDL.Opt(UserId),
  'totalIncome' : IDL.Nat,
  'levelIncome' : IDL.Nat,
  'fullName' : IDL.Text,
  'leftChildId' : IDL.Opt(UserId),
  'isActive' : IDL.Bool,
  'binaryIncome' : IDL.Nat,
  'myReferralCode' : IDL.Text,
  'mobile' : IDL.Text,
  'position' : IDL.Opt(Position),
  'parentId' : IDL.Opt(UserId),
  'leftTeamCount' : IDL.Nat,
  'walletBalance' : IDL.Nat,
  'sponsorCode' : IDL.Text,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : UserId,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'txType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addUserBinaryPosition' : IDL.Func([UserId, UserId, Position], [], []),
  'adminActivateUser' : IDL.Func([UserId, IDL.Bool], [], []),
  'adminApproveWithdraw' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'adminGetPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'adminGetProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'adminGetTotalBusiness' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalIncomeDistributed' : IDL.Nat,
          'totalPlansSold' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalWithdrawals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [SessionToken], []),
  'adminUserList' : IDL.Func([], [IDL.Vec(UserDto)], ['query']),
  'adminVerifyPayment' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateBinaryIncome' : IDL.Func([UserId], [IDL.Nat], []),
  'getBinaryTree' : IDL.Func(
      [UserId],
      [
        IDL.Opt(
          IDL.Record({
            'left' : IDL.Opt(UserDto),
            'user' : UserDto,
            'right' : IDL.Opt(UserDto),
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserDashboard' : IDL.Func(
      [SessionToken],
      [IDL.Opt(DashboardStats)],
      ['query'],
    ),
  'getUserIncomeRecords' : IDL.Func(
      [SessionToken],
      [IDL.Vec(IncomeRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileById' : IDL.Func([SessionToken], [IDL.Opt(User)], ['query']),
  'getUserWalletHistory' : IDL.Func(
      [SessionToken],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUserByMobile' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'submitPayment' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([SessionToken, IDL.Text], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'withdrawRequest' : IDL.Func([SessionToken, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Position = IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'verified' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'planId' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : IDL.Int,
    'upiRef' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const SessionToken = IDL.Text;
  const UserDto = IDL.Record({
    'id' : UserId,
    'directIncome' : IDL.Nat,
    'planId' : IDL.Nat,
    'rightTeamCount' : IDL.Nat,
    'joinedAt' : IDL.Int,
    'totalIncome' : IDL.Nat,
    'levelIncome' : IDL.Nat,
    'fullName' : IDL.Text,
    'binaryIncome' : IDL.Nat,
    'myReferralCode' : IDL.Text,
    'mobile' : IDL.Text,
    'leftTeamCount' : IDL.Nat,
    'walletBalance' : IDL.Nat,
    'sponsorCode' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'fullName' : IDL.Text,
    'myReferralCode' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Plan = IDL.Record({
    'id' : IDL.Nat,
    'levelIncomeRates' : IDL.Vec(IDL.Nat),
    'directIncomePercent' : IDL.Nat,
    'name' : IDL.Text,
    'binaryIncomePercent' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const IncomeRecord = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : IDL.Int,
    'level' : IDL.Opt(IDL.Nat),
    'fromUserId' : UserId,
    'incomeType' : IDL.Variant({
      'level' : IDL.Null,
      'direct' : IDL.Null,
      'binary' : IDL.Null,
    }),
    'amount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'directReferrals' : IDL.Nat,
    'rightTeamCount' : IDL.Nat,
    'totalIncome' : IDL.Nat,
    'totalTeam' : IDL.Nat,
    'recentIncomeRecords' : IDL.Vec(IncomeRecord),
    'leftTeamCount' : IDL.Nat,
    'walletBalance' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : UserId,
    'directIncome' : IDL.Nat,
    'planId' : IDL.Nat,
    'rightTeamCount' : IDL.Nat,
    'joinedAt' : IDL.Int,
    'rightChildId' : IDL.Opt(UserId),
    'totalIncome' : IDL.Nat,
    'levelIncome' : IDL.Nat,
    'fullName' : IDL.Text,
    'leftChildId' : IDL.Opt(UserId),
    'isActive' : IDL.Bool,
    'binaryIncome' : IDL.Nat,
    'myReferralCode' : IDL.Text,
    'mobile' : IDL.Text,
    'position' : IDL.Opt(Position),
    'parentId' : IDL.Opt(UserId),
    'leftTeamCount' : IDL.Nat,
    'walletBalance' : IDL.Nat,
    'sponsorCode' : IDL.Text,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : UserId,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'txType' : IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null }),
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addUserBinaryPosition' : IDL.Func([UserId, UserId, Position], [], []),
    'adminActivateUser' : IDL.Func([UserId, IDL.Bool], [], []),
    'adminApproveWithdraw' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'adminGetPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'adminGetProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'adminGetTotalBusiness' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalIncomeDistributed' : IDL.Nat,
            'totalPlansSold' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalWithdrawals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [SessionToken], []),
    'adminUserList' : IDL.Func([], [IDL.Vec(UserDto)], ['query']),
    'adminVerifyPayment' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateBinaryIncome' : IDL.Func([UserId], [IDL.Nat], []),
    'getBinaryTree' : IDL.Func(
        [UserId],
        [
          IDL.Opt(
            IDL.Record({
              'left' : IDL.Opt(UserDto),
              'user' : UserDto,
              'right' : IDL.Opt(UserDto),
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserDashboard' : IDL.Func(
        [SessionToken],
        [IDL.Opt(DashboardStats)],
        ['query'],
      ),
    'getUserIncomeRecords' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IncomeRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileById' : IDL.Func([SessionToken], [IDL.Opt(User)], ['query']),
    'getUserWalletHistory' : IDL.Func(
        [SessionToken],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUserByMobile' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'submitPayment' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([SessionToken, IDL.Text], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'withdrawRequest' : IDL.Func([SessionToken, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };