/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export interface Plan {
    id: bigint;
    levelIncomeRates: Array<bigint>;
    directIncomePercent: bigint;
    name: string;
    binaryIncomePercent: bigint;
    price: bigint;
}
export interface IncomeRecord {
    id: bigint;
    userId: UserId;
    createdAt: bigint;
    level?: bigint;
    fromUserId: UserId;
    incomeType: Variant_level_direct_binary;
    amount: bigint;
}
export interface User {
    id: UserId;
    directIncome: bigint;
    planId: bigint;
    rightTeamCount: bigint;
    joinedAt: bigint;
    rightChildId?: UserId;
    totalIncome: bigint;
    levelIncome: bigint;
    fullName: string;
    leftChildId?: UserId;
    isActive: boolean;
    binaryIncome: bigint;
    myReferralCode: string;
    mobile: string;
    position?: Position;
    parentId?: UserId;
    leftTeamCount: bigint;
    walletBalance: bigint;
    sponsorCode: string;
    utrNumber: string;
    screenshotUrl: string;
    paymentStatus: PaymentStatus;
}
export type SessionToken = string;
export interface UserDto {
    id: UserId;
    directIncome: bigint;
    planId: bigint;
    rightTeamCount: bigint;
    joinedAt: bigint;
    totalIncome: bigint;
    levelIncome: bigint;
    fullName: string;
    binaryIncome: bigint;
    myReferralCode: string;
    mobile: string;
    leftTeamCount: bigint;
    walletBalance: bigint;
    sponsorCode: string;
    isActive: boolean;
    paymentStatus: PaymentStatus;
}
export interface UserRegistrationDto {
    id: UserId;
    fullName: string;
    mobile: string;
    planId: bigint;
    planName: string;
    planPrice: bigint;
    utrNumber: string;
    screenshotUrl: string;
    paymentStatus: PaymentStatus;
    joinedAt: bigint;
}
export interface WalletTransaction {
    id: bigint;
    status: Variant_pending_approved_rejected;
    userId: UserId;
    note: string;
    createdAt: bigint;
    txType: Variant_credit_debit;
    amount: bigint;
}
export interface Payment {
    id: bigint;
    status: Variant_verified_pending_rejected;
    planId: bigint;
    userId: UserId;
    createdAt: bigint;
    upiRef: string;
    amount: bigint;
}
export interface DashboardStats {
    directReferrals: bigint;
    rightTeamCount: bigint;
    totalIncome: bigint;
    totalTeam: bigint;
    recentIncomeRecords: Array<IncomeRecord>;
    leftTeamCount: bigint;
    walletBalance: bigint;
}
export interface UserProfile {
    userId: string;
    fullName: string;
    myReferralCode: string;
    mobile: string;
}
export interface Product {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: string;
    price: bigint;
}
export enum Position {
    left = "left",
    right = "right"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_credit_debit {
    credit = "credit",
    debit = "debit"
}
export enum Variant_level_direct_binary {
    level = "level",
    direct = "direct",
    binary = "binary"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_verified_pending_rejected {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum PaymentStatus {
    pendingVerification = "pendingVerification",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(adminToken: string, name: string, description: string, price: bigint, imageUrl: string): Promise<bigint>;
    addUserBinaryPosition(userId: UserId, parentId: UserId, position: Position): Promise<void>;
    adminActivateUser(adminToken: string, userId: UserId, isActive: boolean): Promise<void>;
    adminApproveRegistration(adminToken: string, userId: UserId, approved: boolean): Promise<void>;
    adminApproveWithdraw(adminToken: string, txId: bigint, approved: boolean): Promise<void>;
    adminDeleteUser(adminToken: string, userId: string): Promise<void>;
    adminUpdateUser(adminToken: string, userId: string, fullName: string, mobile: string): Promise<void>;
    adminGetPayments(adminToken: string): Promise<Array<Payment>>;
    adminGetPendingRegistrations(adminToken: string): Promise<Array<UserRegistrationDto>>;
    adminGetProducts(adminToken: string): Promise<Array<Product>>;
    adminGetTotalBusiness(adminToken: string): Promise<{
        totalIncomeDistributed: bigint;
        totalPlansSold: bigint;
        totalUsers: bigint;
        totalWithdrawals: bigint;
    }>;
    adminLogin(password: string): Promise<SessionToken>;
    adminUserList(adminToken: string): Promise<Array<UserDto>>;
    adminVerifyPayment(adminToken: string, paymentId: bigint, verified: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateBinaryIncome(userId: UserId): Promise<bigint>;
    getBinaryTree(userId: UserId): Promise<{
        left?: UserDto;
        user: UserDto;
        right?: UserDto;
    } | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPlans(): Promise<Array<Plan>>;
    getProducts(): Promise<Array<Product>>;
    getUserDashboard(sessionToken: SessionToken): Promise<DashboardStats | null>;
    getUserIncomeRecords(sessionToken: SessionToken): Promise<Array<IncomeRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfileById(sessionToken: SessionToken): Promise<User | null>;
    getUserWalletHistory(sessionToken: SessionToken): Promise<Array<WalletTransaction>>;
    isCallerAdmin(): Promise<boolean>;
    loginUserByMobile(mobile: string, otp: string): Promise<SessionToken>;
    registerUser(fullName: string, mobile: string, sponsorCode: string, planId: bigint, utrNumber: string, screenshotUrl: string, password: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendOTP(mobile: string): Promise<string>;
    submitPayment(sessionToken: SessionToken, planId: bigint, upiRef: string): Promise<bigint>;
    updateProduct(adminToken: string, productId: bigint, name: string, description: string, price: bigint, imageUrl: string, isActive: boolean): Promise<void>;
    updateUserProfile(sessionToken: SessionToken, fullName: string): Promise<void>;
    verifyOTP(mobile: string, otp: string): Promise<boolean>;
    withdrawRequest(sessionToken: SessionToken, amount: bigint): Promise<bigint>;
}
import type { DashboardStats as _DashboardStats, IncomeRecord as _IncomeRecord, Payment as _Payment, PaymentStatus_candid as _PaymentStatus_candid, Position as _Position, User as _User, UserDto as _UserDto, UserRegistrationDto as _UserRegistrationDto, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WalletTransaction as _WalletTransaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addUserBinaryPosition(arg0: UserId, arg1: UserId, arg2: Position): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserBinaryPosition(arg0, arg1, to_candid_Position_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserBinaryPosition(arg0, arg1, to_candid_Position_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminActivateUser(arg0: string, arg1: UserId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminActivateUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminActivateUser(arg0, arg1, arg2);
            return result;
        }
    }
    async adminApproveRegistration(arg0: string, arg1: UserId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveRegistration(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveRegistration(arg0, arg1, arg2);
            return result;
        }
    }
    async adminApproveWithdraw(arg0: string, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveWithdraw(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveWithdraw(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeleteUser(arg0: string, arg1: string): Promise<void> {
        try { await (this.actor as any).adminDeleteUser(arg0, arg1); } catch (e) { if (this.processError) this.processError(e); }
    }
    async adminUpdateUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        try { await (this.actor as any).adminUpdateUser(arg0, arg1, arg2, arg3); } catch (e) { if (this.processError) this.processError(e); }
    }
    async adminGetPayments(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPayments(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPayments(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetPendingRegistrations(arg0: string): Promise<Array<UserRegistrationDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingRegistrations(arg0);
                return from_candid_vec_registrations(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingRegistrations(arg0);
            return from_candid_vec_registrations(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetProducts(arg0);
            return result;
        }
    }
    async adminGetTotalBusiness(arg0: string): Promise<{
        totalIncomeDistributed: bigint;
        totalPlansSold: bigint;
        totalUsers: bigint;
        totalWithdrawals: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetTotalBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetTotalBusiness(arg0);
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<SessionToken> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async adminUserList(arg0: string): Promise<Array<UserDto>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUserList(arg0);
                return from_candid_vec_userdto(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUserList(arg0);
            return from_candid_vec_userdto(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminVerifyPayment(arg0: string, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminVerifyPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminVerifyPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateBinaryIncome(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateBinaryIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateBinaryIncome(arg0);
            return result;
        }
    }
    async getBinaryTree(arg0: UserId): Promise<{
        left?: UserDto;
        user: UserDto;
        right?: UserDto;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinaryTree(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinaryTree(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlans(): Promise<Array<Plan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlans();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getUserDashboard(arg0: SessionToken): Promise<DashboardStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDashboard(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDashboard(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserIncomeRecords(arg0: SessionToken): Promise<Array<IncomeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserIncomeRecords(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserIncomeRecords(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileById(arg0: SessionToken): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileById(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileById(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWalletHistory(arg0: SessionToken): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWalletHistory(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWalletHistory(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginUserByMobile(arg0: string, arg1: string): Promise<SessionToken> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUserByMobile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUserByMobile(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendOTP(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendOTP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendOTP(arg0);
            return result;
        }
    }
    async submitPayment(arg0: SessionToken, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateUserProfile(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1);
            return result;
        }
    }
    async verifyOTP(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOTP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOTP(arg0, arg1);
            return result;
        }
    }
    async withdrawRequest(arg0: SessionToken, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawRequest(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PaymentStatus(_uploadFile: any, _downloadFile: any, value: _PaymentStatus_candid): PaymentStatus {
    return "pendingVerification" in value ? PaymentStatus.pendingVerification : "approved" in value ? PaymentStatus.approved : "rejected" in value ? PaymentStatus.rejected : PaymentStatus.pendingVerification;
}
function from_candid_DashboardStats_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_IncomeRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeRecord): IncomeRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_User_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTransaction_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTransaction): WalletTransaction {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserDto]): UserDto | null {
    return value.length === 0 ? null : from_candid_userdto(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DashboardStats]): DashboardStats | null {
    return value.length === 0 ? null : from_candid_DashboardStats_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Position]): Position | null {
    return value.length === 0 ? null : from_candid_Position_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        left: [] | [_UserDto];
        user: _UserDto;
        right: [] | [_UserDto];
    }]): {
    left?: UserDto;
    user: UserDto;
    right?: UserDto;
} | null {
    return value.length === 0 ? null : from_candid_record_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    left: [] | [_UserDto];
    user: _UserDto;
    right: [] | [_UserDto];
}): {
    left?: UserDto;
    user: UserDto;
    right?: UserDto;
} {
    return {
        left: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.left)),
        user: from_candid_userdto(_uploadFile, _downloadFile, value.user),
        right: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.right))
    };
}
function from_candid_userdto(_uploadFile: any, _downloadFile: any, value: _UserDto): UserDto {
    return {
        id: value.id,
        directIncome: value.directIncome,
        planId: value.planId,
        rightTeamCount: value.rightTeamCount,
        joinedAt: value.joinedAt,
        totalIncome: value.totalIncome,
        levelIncome: value.levelIncome,
        fullName: value.fullName,
        binaryIncome: value.binaryIncome,
        myReferralCode: value.myReferralCode,
        mobile: value.mobile,
        leftTeamCount: value.leftTeamCount,
        walletBalance: value.walletBalance,
        sponsorCode: value.sponsorCode,
        isActive: value.isActive,
        paymentStatus: from_candid_PaymentStatus(_uploadFile, _downloadFile, value.paymentStatus)
    };
}
function from_candid_registration(_uploadFile: any, _downloadFile: any, value: _UserRegistrationDto): UserRegistrationDto {
    return {
        id: value.id,
        fullName: value.fullName,
        mobile: value.mobile,
        planId: value.planId,
        planName: value.planName,
        planPrice: value.planPrice,
        utrNumber: value.utrNumber,
        screenshotUrl: value.screenshotUrl,
        paymentStatus: from_candid_PaymentStatus(_uploadFile, _downloadFile, value.paymentStatus),
        joinedAt: value.joinedAt
    };
}
function from_candid_vec_registrations(_uploadFile: any, _downloadFile: any, value: Array<_UserRegistrationDto>): Array<UserRegistrationDto> {
    return value.map((x) => from_candid_registration(_uploadFile, _downloadFile, x));
}
function from_candid_vec_userdto(_uploadFile: any, _downloadFile: any, value: Array<_UserDto>): Array<UserDto> {
    return value.map((x) => from_candid_userdto(_uploadFile, _downloadFile, x));
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    directReferrals: bigint;
    rightTeamCount: bigint;
    totalIncome: bigint;
    totalTeam: bigint;
    recentIncomeRecords: Array<_IncomeRecord>;
    leftTeamCount: bigint;
    walletBalance: bigint;
}): {
    directReferrals: bigint;
    rightTeamCount: bigint;
    totalIncome: bigint;
    totalTeam: bigint;
    recentIncomeRecords: Array<IncomeRecord>;
    leftTeamCount: bigint;
    walletBalance: bigint;
} {
    return {
        directReferrals: value.directReferrals,
        rightTeamCount: value.rightTeamCount,
        totalIncome: value.totalIncome,
        totalTeam: value.totalTeam,
        recentIncomeRecords: from_candid_vec_n18(_uploadFile, _downloadFile, value.recentIncomeRecords),
        leftTeamCount: value.leftTeamCount,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    createdAt: bigint;
    level: [] | [bigint];
    fromUserId: _UserId;
    incomeType: {
        level: null;
    } | {
        direct: null;
    } | {
        binary: null;
    };
    amount: bigint;
}): {
    id: bigint;
    userId: UserId;
    createdAt: bigint;
    level?: bigint;
    fromUserId: UserId;
    incomeType: Variant_level_direct_binary;
    amount: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        level: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.level)),
        fromUserId: value.fromUserId,
        incomeType: from_candid_variant_n22(_uploadFile, _downloadFile, value.incomeType),
        amount: value.amount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return {
        id: value.id,
        directIncome: value.directIncome,
        planId: value.planId,
        rightTeamCount: value.rightTeamCount,
        joinedAt: value.joinedAt,
        rightChildId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.rightChildId)),
        totalIncome: value.totalIncome,
        levelIncome: value.levelIncome,
        fullName: value.fullName,
        leftChildId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.leftChildId)),
        isActive: value.isActive,
        binaryIncome: value.binaryIncome,
        myReferralCode: value.myReferralCode,
        mobile: value.mobile,
        position: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.position)),
        parentId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.parentId)),
        leftTeamCount: value.leftTeamCount,
        walletBalance: value.walletBalance,
        sponsorCode: value.sponsorCode,
        utrNumber: value.utrNumber,
        screenshotUrl: value.screenshotUrl,
        paymentStatus: from_candid_PaymentStatus(_uploadFile, _downloadFile, value.paymentStatus)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    userId: _UserId;
    note: string;
    createdAt: bigint;
    txType: {
        credit: null;
    } | {
        debit: null;
    };
    amount: bigint;
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    userId: UserId;
    note: string;
    createdAt: bigint;
    txType: Variant_credit_debit;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        note: value.note,
        createdAt: value.createdAt,
        txType: from_candid_variant_n34(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        verified: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    };
    planId: bigint;
    userId: _UserId;
    createdAt: bigint;
    upiRef: string;
    amount: bigint;
}): {
    id: bigint;
    status: Variant_verified_pending_rejected;
    planId: bigint;
    userId: UserId;
    createdAt: bigint;
    upiRef: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n6(_uploadFile, _downloadFile, value.status),
        planId: value.planId,
        userId: value.userId,
        createdAt: value.createdAt,
        upiRef: value.upiRef,
        amount: value.amount
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: null;
} | {
    direct: null;
} | {
    binary: null;
}): Variant_level_direct_binary {
    return "level" in value ? Variant_level_direct_binary.level : "direct" in value ? Variant_level_direct_binary.direct : "binary" in value ? Variant_level_direct_binary.binary : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    left: null;
} | {
    right: null;
}): Position {
    return "left" in value ? Position.left : "right" in value ? Position.right : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): Variant_credit_debit {
    return "credit" in value ? Variant_credit_debit.credit : "debit" in value ? Variant_credit_debit.debit : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): Variant_verified_pending_rejected {
    return "verified" in value ? Variant_verified_pending_rejected.verified : "pending" in value ? Variant_verified_pending_rejected.pending : "rejected" in value ? Variant_verified_pending_rejected.rejected : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncomeRecord>): Array<IncomeRecord> {
    return value.map((x)=>from_candid_IncomeRecord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTransaction>): Array<WalletTransaction> {
    return value.map((x)=>from_candid_WalletTransaction_n31(_uploadFile, _downloadFile, x));
}
function to_candid_Position_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): {
    left: null;
} | {
    right: null;
} {
    return value == Position.left ? {
        left: null
    } : value == Position.right ? {
        right: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
